# Generated by Django 4.0.4 on 2022-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_customer_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBuks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(blank=True, max_length=100)),
                ('std_name', models.CharField(blank=True, max_length=100)),
                ('book_id', models.CharField(max_length=13)),
                ('book_name', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('fine', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
