# Generated by Django 4.0.4 on 2022-06-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryApp', '0003_issuedbuks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedbuks',
            old_name='book_id',
            new_name='bookid',
        ),
        migrations.RenameField(
            model_name='issuedbuks',
            old_name='book_name',
            new_name='bookname',
        ),
        migrations.RenameField(
            model_name='issuedbuks',
            old_name='expiry_date',
            new_name='expdate',
        ),
        migrations.RenameField(
            model_name='issuedbuks',
            old_name='issued_date',
            new_name='isdate',
        ),
        migrations.RenameField(
            model_name='issuedbuks',
            old_name='std_id',
            new_name='stid',
        ),
        migrations.RenameField(
            model_name='issuedbuks',
            old_name='std_name',
            new_name='stname',
        ),
        migrations.AddField(
            model_name='issuedbuks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
