# Generated by Django 4.0.4 on 2022-06-16 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryApp', '0004_rename_book_id_issuedbuks_bookid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsedBuks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=100)),
                ('isdate', models.DateField()),
                ('expdate', models.DateField()),
                ('fine', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IssuedBuks',
        ),
    ]
